apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: manager
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 64Mi
        env:
        - name: ENVIRONMENT
          value: "testing"
        - name: MODEL_TRANSPARENCY_CLI_IMAGE
          value: "ghcr.io/sigstore/model-transparency-cli:latest"
